
export const contractorsData = [
  {
    id: '1',
    name: 'Andy Salas',
    company: 'A & G Electric',
    email: 'salasinc@yahoo.com',
    phone: '713-201-2446',
    type: 'Electrical',
    rating: null,
    status: 'Active',
  },
  {
    id: '2',
    name: 'Carlos Osorto',
    company: 'Carlos',
    email: 'c24871512@gmail.com',
    phone: '832-790-5023',
    type: 'Steel',
    rating: null,
    status: 'Active',
  },
  {
    id: '3',
    name: 'Joseph Jacobs',
    company: 'Jacore Fire',
    email: 'firet1227@gmail.com',
    phone: '832-302-5514',
    type: 'Ansul System',
    rating: null,
    status: 'Active',
  },
  {
    id: '4',
    name: 'Jose Ramirez',
    company: 'Ramirez Construction',
    email: 'jose@ramiriezcons.com',
    phone: '(555) 234-5678',
    type: 'Electrical',
    rating: 4,
    status: 'Active',
  },
  {
    id: '5',
    name: 'Pedro Andrade',
    company: 'Andrade Construction',
    email: 'ess573679@gmail.com',
    phone: '346-852-0794',
    type: 'Stucco/Bricks/Blocks',
    rating: null,
    status: 'Active',
  },
];
