export type BudgetCategory = {
  id: string;
  category: string;
  costType: string;
  notes: string;
};

export const budgetCategoriesData: BudgetCategory[] = [
  { id: '1', category: 'Sitework Labor', costType: 'Sitework', notes: 'Labor' },
  { id: '2', category: 'Sitework Material', costType: 'Sitework', notes: 'Material' },
  { id: '3', category: 'Dirtwork Labor', costType: 'Dirtwork', notes: 'Labor' },
  { id: '4', category: 'Pollution Control Labor', costType: 'Pollution', notes: 'Labor' },
  { id: '5', category: 'Pollution Control Material', costType: 'Pollution', notes: 'Material' },
  { id: '6', category: 'SWPP', costType: 'SWPP', notes: 'SWPP' },
  { id: '7', category: 'Steel Labor', costType: 'Steel', notes: 'Labor' },
  { id: '8', category: 'Steel Material', costType: 'Steel', notes: 'Material' },
  { id: '9', category: 'Haul Off', costType: 'Haul', notes: 'Off' },
  { id: '10', category: 'Foundation Labor', costType: 'Foundation', notes: 'Labor' },
  { id: '11', category: 'Foundation Material', costType: 'Foundation', notes: 'Material' },
  { id: '12', category: 'Parking Lot Labor', costType: 'Parking', notes: 'Labor' },
  { id: '13', category: 'Parking Lot Material', costType: 'Parking', notes: 'Material' },
  { id: '14', category: 'SideWalk Labor', costType: 'SideWalk', notes: 'Labor' },
  { id: '15', category: 'SideWalk Material', costType: 'SideWalk', notes: 'Material' },
  { id: '16', category: 'Curbs Labor', costType: 'Curbs', notes: 'Labor' },
  { id: '17', category: 'Curbs Material', costType: 'Curbs', notes: 'Material' },
  { id: '18', category: 'Bollards/Car-stoppers', costType: 'Bollards', notes: 'stoppers' },
  { id: '19', category: 'Electrical', costType: 'Electrical', notes: 'Electrical' },
  { id: '20', category: 'Plumbing', costType: 'Plumbing', notes: 'Plumbing' },
  { id: '21', category: 'HVAC', costType: 'HVAC', notes: 'HVAC' },
  { id: '22', category: 'Framing Labor', costType: 'Framing', notes: 'Labor' },
  { id: '23', category: 'Framing Material', costType: 'Framing', notes: 'Material' },
  { id: '24', category: 'Doors/Hardware Labor', costType: 'Doors', notes: 'Labor' },
  { id: '25', category: 'Doors/Hardware Material', costType: 'Doors', notes: 'Material' },
  { id: '26', category: 'Roof/Coping/Downspots/CollectorBox', costType: 'Roof', notes: 'CollectorBox' },
  { id: '27', category: 'Store front Canopy Labor', costType: 'Store', notes: 'Labor' },
  { id: '28', category: 'Store front Canopy Material', costType: 'Store', notes: 'Material' },
  { id: '29', category: 'Stucco/Bricks/Burnished Blocks', costType: 'Stucco', notes: 'Blocks' },
  { id: '30', category: 'Store front GLASS', costType: 'Store', notes: 'GLASS' },
  { id: '31', category: 'Floor / Tiles Labor', costType: 'Floor', notes: 'Labor' },
  { id: '32', category: 'Floor / Tiles Material', costType: 'Floor', notes: 'Material' },
  { id: '33', category: 'Paint Labor', costType: 'Paint', notes: 'Labor' },
  { id: '34', category: 'Paint Material', costType: 'Paint', notes: 'Material' },
  { id: '35', category: 'Millwork', costType: 'Millwork', notes: 'Millwork' },
  { id: '36', category: 'VentHood', costType: 'VentHood', notes: 'VentHood' },
  { id: '37', category: 'Ansul System', costType: 'Ansul', notes: 'System' },
  { id: '38', category: 'RENTALS', costType: 'RENTALS', notes: 'RENTALS' },
  { id: '39', category: 'Landscape Labor', costType: 'Landscape', notes: 'Labor' },
  { id: '40', category: 'Landscape Material', costType: 'Landscape', notes: 'Material' },
  { id: '41', category: 'Survey', costType: 'Survey', notes: 'Survey' },
  { id: '42', category: 'Cleanup', costType: 'Cleanup', notes: 'Cleanup' },
  { id: '43', category: 'Stripes Labor', costType: 'Stripes', notes: 'Labor' },
  { id: '44', category: 'Stripes Material', costType: 'Stripes', notes: 'Material' },
  { id: '45', category: 'Misc.', costType: 'Misc', notes: 'Misc.' },
  { id: '46', category: "Builder's Risk", costType: "Builder's", notes: 'Risk' },
  { id: '47', category: 'Administrative/Superintendent Cost', costType: 'Administrative', notes: 'Cost' },
];
