// src/app/(app)/contractors/vendors/vendors-data.ts

export type Vendor = {
  id: string;
  name: string;
  trade: string;
  contactPerson: string;
  phone: string;
  email: string;
};

export const vendorsData: Vendor[] = [
  {
    id: "1",
    name: "A & G Electric",
    trade: "Electric",
    contactPerson: "Andy Slalas",
    phone: "7132012446",
    email: "salasinc@yahoo.com",
  },
  {
    id: "2",
    name: "A Morfin Trucking LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "3",
    name: "ACT PIPE AND SUPPLY, INC.",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "4",
    name: "Action Gypsum",
    trade: "Framing Material",
    contactPerson: "Juan",
    phone: "",
    email: "",
  },
  {
    id: "5",
    name: "Advanced LED Solution",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "6",
    name: "Alexanders Construction",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "7",
    name: "Alif Security LLC",
    trade: "Fire Alarm",
    contactPerson: "Nadim/Allen",
    phone: "",
    email: "",
  },
  {
    id: "8",
    name: "Allied Hydromulch TX, LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "9",
    name: "Amazon",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "10",
    name: "Andrade Construction (Sandra Cruz)",
    trade: "Stucco/Stone/Bricks",
    contactPerson: "Pedro Andrade",
    phone: "",
    email: "",
  },
  {
    id: "11",
    name: "Arise Furniture LLC",
    trade: "Millwork",
    contactPerson: "Hai Vu",
    phone: "",
    email: "",
  },
  {
    id: "12",
    name: "Backflow Technicians",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "13",
    name: "Barreras Glass",
    trade: "Store Front Glass",
    contactPerson: "Miguel",
    phone: "",
    email: "",
  },
  {
    id: "14",
    name: "Brent Lowrey",
    trade: "Superintendent",
    contactPerson: "Brent",
    phone: "",
    email: "",
  },
  {
    id: "15",
    name: "Camarillo Trucks",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "16",
    name: "Cano",
    trade: "Ventood",
    contactPerson: "Cano",
    phone: "",
    email: "",
  },
  {
    id: "17",
    name: "Carlos Osorto",
    trade: "Steel fab. & erector",
    contactPerson: "Carlos",
    phone: "",
    email: "",
  },
  {
    id: "18",
    name: "CNA SURETY",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "19",
    name: "Compania Vision",
    trade: "Fuel & storefront canopy",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "20",
    name: "Concrete Cleaning Inc. (Polished Concrete)",
    trade: "Polish concrete",
    contactPerson: "Randy",
    phone: "",
    email: "",
  },
  {
    id: "21",
    name: "Crow Castle LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "22",
    name: "CUSTOM BUILDS & RENTALS, LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "23",
    name: "Dumpster Dogs TX",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "24",
    name: "Dynamic Fastener",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "25",
    name: "ECUA Homes (Sand+Stabulizer)",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "26",
    name: "Eloy Torres",
    trade: "CMU blocks",
    contactPerson: "Eloy",
    phone: "",
    email: "",
  },
  {
    id: "27",
    name: "Enrique Arteaga",
    trade: "Concrete/UG",
    contactPerson: "Enrique",
    phone: "",
    email: "",
  },
  {
    id: "28",
    name: "Equadors Trucking Services",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "29",
    name: "Fabco",
    trade: "Sitework material",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "30",
    name: "Final Inspection 11/4/2024",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "31",
    name: "Fire Sprinkler System",
    trade: "Fire Sprinkler",
    contactPerson: "Allen/Sayed",
    phone: "",
    email: "",
  },
  {
    id: "32",
    name: "Fire Sprinkler Texas",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "33",
    name: "Floor & Decor",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "34",
    name: "Frank Gonzalez",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "35",
    name: "Gabriel Pena",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "36",
    name: "GC Rebar",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "37",
    name: "Glavatec Inc.",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "38",
    name: "GM Commercial Services",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "39",
    name: "Gomez MGS (Moises Gomez)",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "40",
    name: "Grainger",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "41",
    name: "H2ECO Bulk LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "42",
    name: "HC Empire Drywall",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "43",
    name: "Henry Osorto",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "44",
    name: "Home Depot",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "45",
    name: "Hunton AC Units Trane",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "46",
    name: "Israel Figueroa",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "47",
    name: "Jacore Fire Protection Co.",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "48",
    name: "Jorge De Los Santos",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "49",
    name: "Jose Ramirez",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "50",
    name: "Juan F. Harnandez",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "51",
    name: "Juan Molina",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "52",
    name: "Juan Valadez",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "53",
    name: "KES Landscaping LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "54",
    name: "L & G Equipment Rentals Inc.",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "55",
    name: "Leon Plumbing",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "56",
    name: "Lone Star Mapping LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "57",
    name: "Longhorn Texas Supply",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "58",
    name: "LP Drilling, Texas City",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "59",
    name: "Makmo Design LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "60",
    name: "MBCI",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "61",
    name: "Norris Mechanical Services & More",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "62",
    name: "Point Equipment Rental",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "63",
    name: "Precision Concrete Pumping LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "64",
    name: "Pye Barker Fire & Safety",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "65",
    name: "Quality Tles",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "66",
    name: "Quick Waste",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "67",
    name: "Red River Storm Water",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "68",
    name: "Revels Brick Company Inc.",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "69",
    name: "Reynaldo Benitez",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "70",
    name: "Ricardo Rodriguez",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "71",
    name: "Rodolfo Ladesma",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "72",
    name: "Rodrigos Concrete Cuts & Cores",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "73",
    name: "Roto Rooter",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "74",
    name: "Sam's Club",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "75",
    name: "Sandra Cruz",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "76",
    name: "Sapo Engineering",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "77",
    name: "Sherwin Williams",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "78",
    name: "South Houston Concrete Pipe Co.",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "79",
    name: "Stainless Kitchen & More",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "80",
    name: "Strifes Air Conditioning & Heating",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "81",
    name: "Sylvia Valadez",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "82",
    name: "Tejas Materials, Inc.",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "83",
    name: "Texas Contracting Consultants",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "84",
    name: "Texas Shield Roofing LLC",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "85",
    name: "Texcon Ready Mix Inc.",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "86",
    name: "The Kings Transport",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "87",
    name: "The Murillo Company",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "88",
    name: "TO BE PAID",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "89",
    name: "Triple S",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "90",
    name: "Tulio Linares",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "91",
    name: "United Rentals",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
  {
    id: "92",
    name: "Victor Rodriguez",
    trade: "",
    contactPerson: "",
    phone: "",
    email: "",
  },
];
