
export const tasksData = [
  {
    id: '1',
    status: 'pending',
    task: 'Pollution Control',
    description: 'Someone to install the silt fences today not on Aug 5th 2025 due to having to cut the trees on the property line.',
    project: '8845 W Adams Avenue',
    priority: 'High',
    dueDate: 'Aug 5, 2025',
    overdue: false,
    assignedTo: 'Contractor 3',
    assigneeType: 'contractor',
    avatarUrl: 'https://picsum.photos/seed/c3/40',
    avatarFallback: 'C3',
  },
  {
    id: '2',
    status: 'completed',
    task: 'Clear Land',
    description: 'Clear and haul off the vegetations. Recieved the equipment on 08/11/2025 will start the scraping and will be done by 08/18/2025',
    project: '8845 W Adams Avenue',
    priority: 'Medium',
    dueDate: 'Aug 11, 2025',
    overdue: false,
    assignedTo: 'asif fancy',
    assigneeType: 'team',
    avatarUrl: 'https://picsum.photos/seed/user1/40',
    avatarFallback: 'AF',
  },
  {
    id: '3',
    status: 'pending',
    task: 'Electrical Underground',
    description: 'Start running the electrical underground conduits',
    project: '8845 W Adams Avenue',
    priority: 'Medium',
    dueDate: 'Aug 19, 2025',
    overdue: true,
    assignedTo: 'Contractor 2',
    assigneeType: 'contractor',
    avatarUrl: 'https://picsum.photos/seed/c2/40',
    avatarFallback: 'C2',
  },
  {
    id: '4',
    status: 'pending',
    task: 'Plumbing Underground',
    description: 'Start making trenches for the underground pipes',
    project: '8845 W Adams Avenue',
    priority: 'Medium',
    dueDate: 'Aug 20, 2025',
    overdue: true,
    assignedTo: 'Contractor 1',
    assigneeType: 'contractor',
    avatarUrl: 'https://picsum.photos/seed/c1/40',
    avatarFallback: 'C1',
  },
  {
    id: '5',
    status: 'completed',
    task: 'Order Fabricated Steel',
    description: 'Order from Rubiano',
    project: '8845 W Adams Avenue',
    priority: 'High',
    dueDate: 'Aug 20, 2025',
    overdue: false,
    assignedTo: 'asif fancy',
    assigneeType: 'team',
    avatarUrl: 'https://picsum.photos/seed/user1/40',
    avatarFallback: 'AF',
  },
  {
    id: '6',
    status: 'completed',
    task: 'Start forming FOUNDATION',
    description: 'From foundation and wait for the electrical and plumbing underground work to be finished.',
    project: '8845 W Adams Avenue',
    priority: 'Medium',
    dueDate: 'Aug 27, 2025',
    overdue: false,
    assignedTo: 'asif fancy',
    assigneeType: 'team',
    avatarUrl: 'https://picsum.photos/seed/user1/40',
    avatarFallback: 'AF',
  },
  {
    id: '7',
    status: 'pending',
    task: 'Foundation piers',
    description: 'Drill piers',
    project: '8845 W Adams Avenue',
    priority: 'High',
    dueDate: 'Aug 29, 2025',
    overdue: false,
    assignedTo: 'asif fancy',
    assigneeType: 'team',
    avatarUrl: 'https://picsum.photos/seed/user1/40',
    avatarFallback: 'AF',
  },
  {
    id: '8',
    status: 'pending',
    task: 'POUR foundation',
    description: 'Pour slab',
    project: '8845 W Adams Avenue',
    priority: 'Medium',
    dueDate: 'Aug 30, 2025',
    overdue: true,
    assignedTo: 'Contractor 3',
    assigneeType: 'contractor',
    avatarUrl: 'https://picsum.photos/seed/c3/40',
    avatarFallback: 'C3',
  },
  {
    id: '9',
    status: 'pending',
    task: 'Erect Steel',
    description: 'Start main building erection',
    project: '8845 W Adams Avenue',
    priority: 'Medium',
    dueDate: 'Sep 3, 2025',
    overdue: false,
    assignedTo: 'Unassigned',
    assigneeType: 'unassigned',
  },
];
