
export type Vendor = {
  id: string;
  name: string;
  company: string;
  email: string;
  phone: string;
  type: string;
  rating: number | null;
  status: 'Active' | 'Inactive';
};

export const vendorsData: Vendor[] = [
    {
        id: '1',
        company: 'A & G Electric',
        type: 'Electric',
        name: 'Andy Slalas',
        phone: '713-201-2446',
        email: 'salasinc@yahoo.com',
        rating: null,
        status: 'Active',
    },
    {
        id: '2',
        company: 'A Morfin Trucking LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '3',
        company: 'ACT PIPE AND SUPPLY, INC.',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '4',
        company: 'Action Gypsum',
        type: 'Framing Material',
        name: 'Juan',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '5',
        company: 'ADE Steel Supply Inc.',
        type: 'Steel decking',
        name: 'Rick - Ricardo Martinez',
        phone: '281-630-9187',
        email: 'rick@adesteelcorp.com',
        rating: null,
        status: 'Active',
    },
    {
        id: '6',
        company: 'Advanced LED Solution',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '7',
        company: 'Alexanders Construction',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '8',
        company: 'Alif Security LLC',
        type: 'Fire Alarm',
        name: 'Nadim/Allen',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '9',
        company: 'Allied Hydromulch TX, LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '10',
        company: 'Amazon',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '11',
        company: 'Andrade Construction (Sandra Cruz)',
        type: 'Stucco/Stone/Bricks',
        name: 'Pedro Andrade',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '12',
        company: 'Arise Furniture LLC',
        type: 'Millwork',
        name: 'Hai Vu',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '13',
        company: 'Backflow Technicians',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '14',
        company: 'Barreras Glass',
        type: 'Store Front Glass',
        name: 'Miguel',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '15',
        company: 'Brent Lowrey',
        type: 'Superintendent',
        name: 'Brent',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '16',
        company: 'Camarillo Trucks',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '17',
        company: 'Cano',
        type: 'Venthood',
        name: 'Cano',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '18',
        company: 'Carlos Osorto',
        type: 'Steel fab. & erector',
        name: 'Carlos',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '19',
        company: 'City Of League City',
        type: 'City',
        name: '',
        phone: '',
        email: 'leaguecity@gmail.com',
        rating: null,
        status: 'Active',
    },
    {
        id: '20',
        company: 'City Of Temple TX',
        type: 'Uncategorized',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '21',
        company: 'CNA SURETY',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '22',
        company: 'Compania Vision',
        type: 'Fuel & storefront canopy',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '23',
        company: 'Concrete Cleaning Inc. (Polished Concrete)',
        type: 'Polish concrete',
        name: 'Randy',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '24',
        company: 'Crow Castle LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '25',
        company: 'CUSTOM BUILDS & RENTALS, LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '26',
        company: 'Dumpster Dogs TX',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '27',
        company: 'Dynamic Fastener',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '28',
        company: 'ECUA Homes (Sand+Stabulizer)',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '29',
        company: 'Eloy Torres',
        type: 'CMU blocks',
        name: 'Eloy',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '30',
        company: 'Enrique Arteaga',
        type: 'Concrete/UG',
        name: 'Enrique',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '31',
        company: 'Equadors Trucking Services',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '32',
        company: 'Fabco',
        type: 'Sitework material',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '33',
        company: 'Final Inspection 11/4/2024',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '34',
        company: 'Fire Sprinkler System',
        type: 'Fire Sprinkler',
        name: 'Allen/Sayed',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '35',
        company: 'Fire Sprinkler Texas',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '36',
        company: 'Floor & Decor',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '37',
        company: 'Frank Gonzalez',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '38',
        company: 'Frank Villarreal',
        type: 'Uncategorized',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '39',
        company: 'Gabriel Pena',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '40',
        company: 'GC Rebar',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '41',
        company: 'Glavatec Inc.',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '42',
        company: 'GM Commercial Services',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '43',
        company: 'Gomez MGS (Moises Gomez)',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '44',
        company: 'Grainger',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '45',
        company: 'H2ECO Bulk LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '46',
        company: 'HC Empire Drywall',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '47',
        company: 'Henry Osorto',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '48',
        company: 'Home Depot',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '49',
        company: 'Hunton AC Units Trane',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '50',
        company: 'Israel Figueroa',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '51',
        company: 'Jacore Fire Protection Co.',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '52',
        company: 'JBA Drilling',
        type: 'Drilling',
        name: 'Juan',
        phone: '1',
        email: 'jba@gmail.com',
        rating: null,
        status: 'Active',
    },
    {
        id: '53',
        company: 'Jorge De Los Santos',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '54',
        company: 'Jose Ramirez',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '55',
        company: 'Juan F. Harnandez',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '56',
        company: 'Juan Molina',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '57',
        company: 'Juan Valadez',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '58',
        company: 'KES Landscaping LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '59',
        company: 'L & G Equipment Rentals Inc.',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '60',
        company: 'Leon Plumbing',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '61',
        company: 'Lone Star Mapping LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '62',
        company: 'Longhorn Texas Supply',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '63',
        company: 'LP Drilling, Texas City',
        type: 'N/A',
        name: 'N/A',
        phone: 'N/A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '64',
        company: 'Makmo Design LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '65',
        company: 'MBCI',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '66',
        company: 'Norris Mechanical Services & More',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '67',
        company: 'Oak Rental LLC.',
        type: 'Equipment Rentals',
        name: 'Brian',
        phone: '1',
        email: 'b@gmail.com',
        rating: null,
        status: 'Active',
    },
    {
        id: '68',
        company: 'Point Equipment Rental',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '69',
        company: 'Precision Concrete Pumping LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '70',
        company: 'Pye Barker Fire & Safety',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '71',
        company: 'Quality Tles',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '72',
        company: 'Quality Truf',
        type: 'Landscape',
        name: 'Heather',
        phone: '8003922010',
        email: 'Qualitytruf@gmail.com',
        rating: null,
        status: 'Active',
    },
    {
        id: '73',
        company: 'Quick Waste',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '74',
        company: 'Red River Storm Water',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '75',
        company: 'Revels Brick Company Inc.',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '76',
        company: 'Reynaldo Benitez',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '77',
        company: 'Ricardo Rodriguez',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '78',
        company: 'Rodolfo Ladesma',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '79',
        company: 'Rodrigos Concrete Cuts & Cores',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '80',
        company: 'Roto Rooter',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '81',
        company: "Sam's Club",
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '82',
        company: 'Sandra Cruz',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '83',
        company: 'Sapo Engineering',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '84',
        company: 'SD Construction Material',
        type: 'Uncategorized',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '85',
        company: 'Sherwin Williams',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '86',
        company: 'South Houston Concrete Pipe Co.',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '87',
        company: 'Stainless Kitchen & More',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '88',
        company: 'Strifes Air Conditioning & Heating',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '89',
        company: 'Sunrise Creek Pumping, LLC',
        type: 'Uncategorized',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '90',
        company: 'Sylvia Valadez',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '91',
        company: 'Tejas Materials, Inc.',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '92',
        company: 'Tex Mix Concrete Mix',
        type: 'Concrete',
        name: 'a',
        phone: '2',
        email: 'noreply@trustcommerce.com',
        rating: null,
        status: 'Active',
    },
    {
        id: '93',
        company: 'Texas Contracting Consultants',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '94',
        company: 'Texas Shield Roofing LLC',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
},
    {
        id: '95',
        company: 'Texcon Ready Mix Inc.',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '96',
        company: 'The Kings Transport',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '97',
        company: 'The Murillo Company',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '98',
        company: 'TO BE PAID',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '99',
        company: 'Triple-S Steel Holdings Inc',
        type: 'Steel',
        name: 'Mirriam Rendino',
        phone: '713-354-4137',
        email: 'Miriam.Rendino@sss-steel.com',
        rating: null,
        status: 'Active',
    },
    {
        id: '100',
        company: 'Tulio Linares',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '101',
        company: 'Uinted Rentals',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
    {
        id: '102',
        company: 'Victor Rodriguez',
        type: 'N/A',
        name: 'N/A',
        phone: 'N_A',
        email: 'N/A',
        rating: null,
        status: 'Active',
    },
];

    